"""
OpenUtau MCP Server: Core Tools Implementation
Modern OpenUtau (.ustx) vocal generation, inspection, expression tuning,
and acoustic synthesis tools for AI Agents and DAWs.
"""

import os
import sys
import json
import yaml
import numpy as np
import soundfile as sf

DEFAULT_VOICEBANK = r"F:\antigravity lol\antigravity-p\voicebanks\teto_tandoku"
DEFAULT_MORESAMPLER = r"F:\antigravity lol\antigravity-p\utau_engines\moresampler.exe"


def midi_num_to_tone(m):
    notes = ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B']
    octave = (m // 12) - 1
    return f"{notes[m % 12]}{octave}"


def tone_to_midi_num(tone):
    notes = {'C': 0, 'C#': 1, 'D': 2, 'D#': 3, 'E': 4, 'F': 5, 'F#': 6, 'G': 7, 'G#': 8, 'A': 9, 'A#': 10, 'B': 11}
    t = str(tone).upper().strip()
    if len(t) >= 2 and t[:2] in notes:
        return (int(t[2:]) + 1) * 12 + notes[t[:2]]
    elif len(t) >= 1 and t[:1] in notes:
        return (int(t[1:]) + 1) * 12 + notes[t[:1]]
    return 60


def tool_openutau_build_ustx(title, bpm, tracks_config, output_ustx_path):
    ustx_tracks = []
    ustx_parts = []

    for t_idx, t in enumerate(tracks_config):
        track_name = t.get("name", f"Track {t_idx+1}")
        singer = t.get("singer", "Kasane Teto [UTAU]")
        phoneticizer = t.get("phoneticizer", "OpenUtau.Core.DefaultPhoneticizer")
        renderer = t.get("renderer", "CLASSIC")

        ustx_tracks.append({
            "singer": singer,
            "phoneticizer": phoneticizer,
            "renderer_settings": {
                "renderer": renderer,
                "resampler": "moresampler.exe"
            },
            "track_name": track_name,
            "track_color": "Blue" if t_idx == 0 else "Purple",
            "mute": False,
            "solo": False,
            "volume": 0.0,
            "pan": 0.0
        })

        notes_raw = t.get("notes", [])
        notes_entries = []
        cur_pos = 0
        for n in notes_raw:
            lyric = n.get("lyric", "あ")
            ticks = n.get("ticks", 480)
            pitch = n.get("pitch", 60)
            pitch_num = tone_to_midi_num(pitch) if isinstance(pitch, str) else int(pitch)
            vel = n.get("vel", 100)

            if lyric not in ["R", "r", "", "-"]:
                notes_entries.append({
                    "position": cur_pos,
                    "duration": ticks,
                    "tone": pitch_num,
                    "lyric": lyric,
                    "pitch": {
                        "data": [
                            {"x": -40, "y": 0, "shape": "io"},
                            {"x": 40, "y": 0, "shape": "io"}
                        ],
                        "snap_first": True
                    },
                    "vibrato": {
                        "length": 65,
                        "period": 175,
                        "depth": 25,
                        "in": 15,
                        "out": 15,
                        "shift": 0,
                        "drift": 0,
                        "vol_link": 0
                    }
                })
            cur_pos += ticks

        ustx_parts.append({
            "name": f"{track_name} Part",
            "track_no": t_idx,
            "position": 0,
            "notes": notes_entries
        })

    ustx_data = {
        "name": title,
        "comment": "Generated by OpenVocal-DAW OpenUtau Engine",
        "output_dir": "Vocal",
        "cache_dir": "Cache",
        "ustx_version": "0.6",
        "bpm": float(bpm),
        "beat_per_bar": 4,
        "beat_unit": 4,
        "resolution": 480,
        "tracks": ustx_tracks,
        "voice_parts": ustx_parts,
        "curves": []
    }

    d = os.path.dirname(output_ustx_path)
    if d: os.makedirs(d, exist_ok=True)
    with open(output_ustx_path, "w", encoding="utf-8") as f:
        yaml.dump(ustx_data, f, allow_unicode=True, sort_keys=False, default_flow_style=False)

    return {
        "status": "success",
        "title": title,
        "bpm": bpm,
        "total_tracks": len(ustx_tracks),
        "total_notes": sum(len(p["notes"]) for p in ustx_parts),
        "ustx_path": output_ustx_path
    }


def tool_openutau_inspect_project(ustx_path):
    if not os.path.exists(ustx_path):
        return {"error": f"Project file not found: {ustx_path}"}
    with open(ustx_path, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f)

    tracks = data.get("tracks", [])
    parts = data.get("voice_parts", [])
    total_notes = sum(len(p.get("notes", [])) for p in parts)

    return {
        "status": "success",
        "name": data.get("name"),
        "ustx_version": data.get("ustx_version"),
        "bpm": data.get("bpm"),
        "resolution": data.get("resolution", 480),
        "tracks_count": len(tracks),
        "tracks_summary": [
            {
                "track_no": i,
                "name": t.get("track_name"),
                "singer": t.get("singer"),
                "phoneticizer": t.get("phoneticizer")
            } for i, t in enumerate(tracks)
        ],
        "total_notes": total_notes
    }


def tool_openutau_tune_expression(dynamics_points=None, tension_points=None, breathiness_points=None, vibrato_depth=25, vibrato_period=175):
    curves = []
    if dynamics_points:
        curves.append({"id": "dyn", "points": dynamics_points})
    if tension_points:
        curves.append({"id": "tns", "points": tension_points})
    if breathiness_points:
        curves.append({"id": "bre", "points": breathiness_points})

    return {
        "status": "success",
        "vibrato": {
            "length": 65,
            "period": vibrato_period,
            "depth": vibrato_depth,
            "in": 15,
            "out": 15
        },
        "expression_curves": curves
    }


def tool_openutau_convert_blueprint(blueprint_path, output_ustx_path):
    with open(blueprint_path, "r", encoding="utf-8") as f:
        bp = json.load(f)

    title = bp.get("title", "Untitled")
    bpm = float(bp.get("bpm", 128.0))
    total_bars = int(bp.get("total_bars", 88))
    vocal_score = bp.get("vocal_score", {})

    notes_list = []
    for b in range(total_bars):
        bar_notes = vocal_score.get(str(b), [])
        for lyric, ticks, pitch, vel in bar_notes:
            notes_list.append({"lyric": lyric, "ticks": ticks, "pitch": pitch, "vel": vel})

    tracks_config = [
        {
            "name": "Lead Vocal",
            "singer": "Kasane Teto [UTAU]",
            "phoneticizer": "OpenUtau.Core.DefaultPhoneticizer",
            "notes": notes_list
        }
    ]
    return tool_openutau_build_ustx(title, bpm, tracks_config, output_ustx_path)


def tool_openutau_synthesize_preview(notes_list, bpm=128.0, output_path="export/openutau_preview.wav"):
    sr = 44100
    sec_per_beat = 60.0 / bpm
    total_ticks = sum(n.get("ticks", 480) for n in notes_list)
    total_samples = int(round((total_ticks / 480.0) * sec_per_beat * sr))
    buffer = np.zeros(total_samples + sr, dtype=np.float32)

    cur_sample = 0
    fade_len = int(0.025 * sr)
    for n in notes_list:
        lyric = n.get("lyric", "あ")
        pitch = n.get("pitch", 60)
        ticks = n.get("ticks", 480)
        vel = n.get("vel", 100)
        dur_ms = int(round((ticks / 480.0) * sec_per_beat * 1000.0))
        dur_samples = int((dur_ms / 1000.0) * sr)

        if lyric not in ["R", "r", "", "-"]:
            pitch_num = tone_to_midi_num(pitch) if isinstance(pitch, str) else int(pitch)
            t = np.linspace(0, dur_ms / 1000.0, dur_samples, endpoint=False)
            freq = 440.0 * (2.0 ** ((pitch_num - 69) / 12.0))
            audio = (
                0.52 * np.sin(2 * np.pi * freq * t) +
                0.26 * np.sin(2 * np.pi * 2 * freq * t) +
                0.14 * np.sin(2 * np.pi * 3 * freq * t) +
                0.08 * np.sin(2 * np.pi * 4 * freq * t)
            ).astype(np.float32) * (vel / 100.0)

            f_len = min(fade_len, len(audio) // 3)
            if f_len > 0:
                t_in = np.linspace(0, 1, f_len, endpoint=False)
                audio[:fade_len] *= (np.sin(0.5 * np.pi * t_in) ** 2)
                t_out = np.linspace(0, 1, f_len, endpoint=True)
                audio[-f_len:] *= (np.cos(0.5 * np.pi * t_out) ** 2)

            e_sample = min(len(buffer), cur_sample + len(audio))
            buffer[cur_sample:e_sample] += audio[:e_sample-cur_sample]

        cur_sample += dur_samples

    final_audio = buffer[:cur_sample]
    peak = float(np.max(np.abs(final_audio)))
    if peak > 0: final_audio = (final_audio / peak) * 0.88

    d = os.path.dirname(output_path)
    if d: os.makedirs(d, exist_ok=True)
    sf.write(output_path, final_audio, sr, subtype='PCM_24')

    return {
        "status": "success",
        "bpm": bpm,
        "duration_sec": round(len(final_audio) / sr, 3),
        "peak": round(float(np.max(np.abs(final_audio))), 4),
        "output_path": output_path
    }
